export enum VsComponent {
    VsAccordion = 'VsAccordion',
    VsAvatar = 'VsAvatar',
    VsBlock = 'VsBlock',
    VsButton = 'VsButton',
    VsCheckbox = 'VsCheckbox',
    VsCheckboxNode = 'VsCheckboxNode',
    VsCheckboxSet = 'VsCheckboxSet',
    VsChip = 'VsChip',
    VsConfirm = 'VsConfirm',
    VsContainer = 'VsContainer',
    VsDivider = 'VsDivider',
    VsDrawer = 'VsDrawer',
    VsFileInput = 'VsFileInput',
    VsFocusTrap = 'VsFocusTrap',
    VsFooter = 'VsFooter',
    VsForm = 'VsForm',
    VsHeader = 'VsHeader',
    VsImage = 'VsImage',
    VsIndexView = 'VsIndexView',
    VsIndexItem = 'VsIndexItem',
    VsInput = 'VsInput',
    VsInputWrapper = 'VsInputWrapper',
    VsLabelValue = 'VsLabelValue',
    VsLayout = 'VsLayout',
    VsLoading = 'VsLoading',
    VsMain = 'VsMain',
    VsMessage = 'VsMessage',
    VsModal = 'VsModal',
    VsNotice = 'VsNotice',
    VsPage = 'VsPage',
    VsPagination = 'VsPagination',
    VsProgress = 'VsProgress',
    VsRadio = 'VsRadio',
    VsRadioNode = 'VsRadioNode',
    VsRadioSet = 'VsRadioSet',
    VsResponsive = 'VsResponsive',
    VsSection = 'VsSection',
    VsSelect = 'VsSelect',
    VsSkeleton = 'VsSkeleton',
    VsStepper = 'VsStepper',
    VsSwitch = 'VsSwitch',
    VsTable = 'VsTable',
    VsTabs = 'VsTabs',
    VsTextarea = 'VsTextarea',
    VsTextWrap = 'VsTextWrap',
    VsThemeButton = 'VsThemeButton',
    VsToast = 'VsToast',
    VsToastView = 'VsToastView',
    VsTooltip = 'VsTooltip',
}

export enum VsNode {
    VsModalNode = 'VsModalNode',
}
