export enum VsComponent {
    VsAccordion = 'VsAccordion',
    VsAvatar = 'VsAvatar',
    VsBlock = 'VsBlock',
    VsButton = 'VsButton',
    VsCheckbox = 'VsCheckbox',
    VsCheckboxSet = 'VsCheckboxSet',
    VsChip = 'VsChip',
    VsContainer = 'VsContainer',
    VsDivider = 'VsDivider',
    VsDrawer = 'VsDrawer',
    VsFileInput = 'VsFileInput',
    VsFocusTrap = 'VsFocusTrap',
    VsFooter = 'VsFooter',
    VsForm = 'VsForm',
    VsHeader = 'VsHeader',
    VsImage = 'VsImage',
    VsIndexView = 'VsIndexView',
    VsIndexItem = 'VsIndexItem',
    VsInput = 'VsInput',
    VsInputWrapper = 'VsInputWrapper',
    VsLabelValue = 'VsLabelValue',
    VsLoading = 'VsLoading',
    VsMain = 'VsMain',
    VsMessage = 'VsMessage',
    VsNotice = 'VsNotice',
    VsPage = 'VsPage',
    VsProgress = 'VsProgress',
    VsSection = 'VsSection',
    VsStepper = 'VsStepper',
    VsTabs = 'VsTabs',
    VsTextarea = 'VsTextarea',
    VsTextWrap = 'VsTextWrap',
    VsThemeButton = 'VsThemeButton',
    VsTooltip = 'VsTooltip',
    VsValueTag = 'VsValueTag',
    VsWrapper = 'VsWrapper',
}

export enum UIState {
    Idle = 'idle',
    Success = 'success',
    Info = 'info',
    Error = 'error',
    Warning = 'warning',
    Selected = 'selected',
}
