name: CI

on: push

jobs:
    test-vitest:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn
            - run: yarn test
              working-directory: ./packages/vlossom

    test-storybook:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn
            - name: Install Playwright
              run: npx playwright install --with-deps
            - name: Build Storybook
              run: yarn build-storybook --quiet
              working-directory: ./packages/vlossom
            - name: Serve Storybook and run tests
              run: |
                  npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
                    "npx http-server storybook-static --port 6006 --silent" \
                    "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"
              working-directory: ./packages/vlossom

    build-vlossom:
        needs: [test-vitest, test-storybook]
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn
            - name: Build Vlossom
              run: yarn build
              working-directory: ./packages/vlossom

    build-docs:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn
            - name: Build Docs
              run: yarn build
              working-directory: ./packages/docs
