name: CI

on: push

jobs:
    cache-dependencies:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

    test-vitest:
        needs: cache-dependencies
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - run: npm run test
              working-directory: ./packages/vlossom

    test-storybook:
        needs: cache-dependencies
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Install Playwright
              run: npx playwright install --with-deps
            - name: Build Storybook
              run: npm run build-storybook --quiet
              working-directory: ./packages/vlossom
            - name: Serve Storybook and run tests
              run: |
                  npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
                    "npx http-server storybook-static --port 6006 --silent" \
                    "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook"
              working-directory: ./packages/vlossom

    build-vlossom:
        needs: cache-dependencies
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Build Vlossom
              run: npm run build
              working-directory: ./packages/vlossom

    build-docs:
        needs: cache-dependencies
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Build Docs
              run: npm run build
              working-directory: ./packages/docs
