name: Tests

on: push

jobs:
    test-vitest:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./packages/vlossom
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - name: Install dependencies
              run: npm ci
            - run: npm run test
